# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Développement et sécurité informatique
email: phackt@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ce site est le blog d'un passionné ayant pour but de proposer des articles généralistes ou techniques autour du développement et de la sécurité informatique.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: phackt_ul
github_username:  lepicte

# Build settings
markdown: kramdown

# highlight
highlighter: rouge
